# pyproject.toml

[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxctx"
version = "1.1.6"
description = "Lightweight JAX context for managing collections of parameters and RNG sequences."
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
requires-python = ">=3.10"
authors = [{ name = "Joshua G. Albert", email = "albert@strw.leidenuniv.nl" }]
keywords = ["jax"]
dependencies = [
    "jax",
    "tfp-nightly",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
urls = { "Homepage" = "https://github.com/joshuaalbert/jaxctx" }

[project.optional-dependencies]
tests = [
    "flake8",
    "ruff",
    "pytest",
    "scipy",
]


[tool.setuptools.packages.find]
where = ["src"]
